# Generated by Django 3.2.9 on 2021-11-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tema', max_length=20)),
                ('slug', models.SlugField(help_text='NÃO MEXE AQUI', max_length=22, unique=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
                ('resposta', models.CharField(help_text='Insira a resposta', max_length=40)),
                ('wiki', models.CharField(blank=True, help_text='Link dessa página do Wikipédia', max_length=200, null=True)),
                ('tema', models.ForeignKey(help_text='Qual tema essa palavra faz parte?', on_delete=django.db.models.deletion.CASCADE, to='game.tema')),
            ],
        ),
    ]
